### ISSUE TITLE
Design About Page

### ISSUE THREAD

**Issue by narayan2111** [narayan2111/Front_end#6]
Design About Page for the Website, describing about the codeon Platform and it's projects and scope.
You can add following data or can create your own.

Codeon is a technical club that focuses on building technical skills and fostering a community of like-minded individuals interested in various domains such as Android, Tableau, UI/UX, and web development. Codeon members work on projects in these areas and have the opportunity to conduct  variety of technical events such as hackathons, workshops, speaker series, networking events, and project showcases. As an emerging club, Codeon provides a platform for members to learn, grow, and connect with others who share their passion for technology.

**Comment by maxyank** [comment]
I would like to work on this issue, kindly assign this issue to me

**Comment by narayan2111** [comment]
> I would like to work on this issue, kindly assign this issue to me

Issue is assigned to you successfully, you can start working on this issue.
Best of luck!

**Comment by narayan2111** [comment]
Issue is Completed Successfully
