### ISSUE TITLE
Add Contact us Page

### ISSUE THREAD

**Issue by narayan2111** [narayan2111/Front_end#8]
Design Contact_us Page, adding the social media links of codeon.

**Comment by shiv10000** [comment]
Please assign me the issue to work on

**Comment by narayan2111** [comment]
Issue is assigned to you successfully. Since we don't have actuals links of social media. So, you can create dummy links and information which you think is relevant to the contact us page.
Happy Coding,
Best of luck!

**Comment by narayan2111** [comment]
> Please assign me the issue to work on

Issue is assigned to you successfully. Since we don't have actuals links of social media. So, you can create dummy links and information which you think is relevant to the contact us page.
Happy Coding,
Best of luck!

**Comment by narayan2111** [comment]
Issue is Completed
